name: CI Angular app through Github Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      â€ uses: actions/checkout@v2
      â€ name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      â€ name: Setup
        run: npm ci

      â€ name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
